services:
  backend:
    image: fastapi:todo-app
    container_name: fastapi-todo
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  db:
    image: postgres:15-bullseye
    container_name: postgresql15
    hostname: postgresql15
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./volumes/postgres/config/my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./volumes/postgres/config/data:/var/lib/postgresql/data/pgdata
    # https://hub.docker.com/_/postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    command: -c 'config_file=/etc/postgresql/postgresql.conf'