version: "3"

tasks:
  migrate:
    cmds:
      - cd backend && poetry run alembic upgrade head
    desc: Run database migrations

  run:backend:
    cmds:
      - cd backend && PYTHONPATH=../ poetry run uvicorn web.main:app --host 0.0.0.0 --port 8000 --reload

  build:backend:
    cmds:
      - docker build . -f Dockerfile.backend -t todo-backend:latest && docker compose up -d
    desc: Build the backend image

  build:frontend:
    cmds:
      - cd frontend && npm run dev
    desc: Install frontend dependencies

  build:all:
    cmds:
      - task: build:backend
      - task: build:frontend

  test:backend:
    cmds:
      - poetry run pytest -v -s --cov=backend --cov-report=xml
    desc: Run backend tests

  clean:
    cmds:
      - find . -type d -name __pycache__ -exec rm -rf {} +
