"""Create Todos table

Revision ID: 31c4062c0665
Revises: 
Create Date: 2023-05-02 22:44:49.302225

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '31c4062c0665'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('title', sa.String(length=20), nullable=False),
                    sa.Column('comment', sa.Text(), nullable=False),
                    sa.Column('is_done', sa.Boolean(), nullable=True),
                    sa.Column('create_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
